env:
  browser: true
  es6: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 2017
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - windows
  quotes:
    - error
    - double
  semi:
    - error
    - never
